const GENRES = [
  { name: "Tất cả thể loại", count: 0 },
  { name: "Action", count: 1 },
  { name: "Adult", count: 2 },
  { name: "Adventure", count: 3 },
  { name: "Anime", count: 4 },
  { name: "Chuyển Sinh", count: 5 },
  { name: "Comedy", count: 6 },
  { name: "Comic", count: 7 },
  { name: "Cooking", count: 8 },
  { name: "Cổ Đại", count: 9 },
  { name: "Doujinshi", count: 10 },
  { name: "Drama", count: 11 },
  { name: "Đam Mỹ", count: 12 },
  { name: "Ecchi", count: 13 },
  { name: "Fantasy", count: 14 },
  { name: "Gender Bender", count: 15 },
  { name: "Harem", count: 16 },
  { name: "Historical", count: 17 },
  { name: "Horror", count: 18 },
  { name: "Josei", count: 19 },
  { name: "Live action", count: 20 },
  { name: "Manga", count: 21 },
  { name: "Manhua", count: 22 },
  { name: "Manhwa", count: 23 },
  { name: "Martial Arts", count: 24 },
  { name: "Mature", count: 25 },
  { name: "Mecha", count: 26 },
  { name: "Mystery", count: 27 },
  { name: "Ngôn Tình", count: 28 },
  { name: "One shot", count: 29 },
  { name: "Psychological", count: 30 },
  { name: "Romance", count: 31 },
  { name: "School Life", count: 32 },
  { name: "Sci-fi", count: 33 },
  { name: "Seinen", count: 34 },
  { name: "Shoujo", count: 35 },
  { name: "Shoujo Ai", count: 36 },
  { name: "Shounen", count: 37 },
  { name: "Shounen Ai", count: 38 },
  { name: "Slice of Life", count: 39 },
  { name: "Smut", count: 40 },
  { name: "Soft Yaoi", count: 41 },
  { name: "Soft Yuri", count: 42 },
  { name: "Sports", count: 43 },
  { name: "Supernatural", count: 44 },
  { name: "Tạp chí truyện tranh", count: 45 },
  { name: "Thiếu Nhi", count: 46 },
  { name: "Tragedy", count: 47 },
  { name: "Trinh Thám", count: 48 },
  { name: "Truyện scan", count: 49 },
  { name: "Truyện Màu", count: 50 },
  { name: "Việt Nam", count: 51 },
  { name: "Webtoon", count: 52 },
  { name: "Xuyên Không", count: 53 },
  { name: "16+", count: "16" },
];
const SORT = [
  {
    name: "Truyện mới",
    count: 0,
  },
  {
    name: "Top tháng",
    count: 1,
  },
  {
    name: "Top tuần",
    count: 2,
  },
  {
    name: "Top ngày",
    count: 3,
  },
];

const STATUS = [
  {
    name: "tất cả",
    count: 0,
  },
  {
    name: "đang tiến hành",
    count: 1,
  },
  {
    name: "hoàn thành",
    count: 2,
  },
];
export { GENRES, SORT, STATUS };
